# Generated by Django 4.2.11 on 2025-12-24 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_seed_department_ingest_jobs'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='departmentrecord',
            new_name='core_depart_source__0ab2ee_idx',
            old_name='core_deprecord_source_recorded_idx',
        ),
        migrations.RenameIndex(
            model_name='departmentrecord',
            new_name='core_depart_student_8dbd18_idx',
            old_name='core_deprecord_student_idx',
        ),
    ]
