# Generated by Django 4.2.11 on 2025-12-25 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_password_reset_requests'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='passwordresetrequest',
            new_name='core_passwo_user_id_f12091_idx',
            old_name='core_passwo_user_id_d33f1f_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordresetrequest',
            new_name='core_passwo_code_fd2bc8_idx',
            old_name='core_passwo_code_7f8d9a_idx',
        ),
    ]
