# Generated by Django 4.2.11 on 2025-12-25 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_merge_0015_branches'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailverificationrequest',
            new_name='core_emailv_user_id_63ceb9_idx',
            old_name='core_emailv_user_id_3c2b2d_idx',
        ),
        migrations.RenameIndex(
            model_name='emailverificationrequest',
            new_name='core_emailv_code_1e6dc9_idx',
            old_name='core_emailv_code_53a3b4_idx',
        ),
    ]
